# reproducibility
seed: 42

export: False
float32_matmul_precision: "medium"
# set_determinism_the_old_way: False
top_k: 100

only_test: False

# pl_trainer
pl_trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  num_nodes: 1
  strategy: null
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  val_check_interval: 0.2 # you can specify an int "n" here => validation every "n" steps
  max_epochs: 40
  deterministic: warn
  fast_dev_run: False
  precision: 16
  resume_from_checkpoint: null

# early stopping callback
# "early_stopping_callback: null" will disable early stopping
early_stopping_callback:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_recall@${train.top_k}
  mode: max
  patience: 10

# model_checkpoint_callback
# "model_checkpoint_callback: null" will disable model checkpointing
model_checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_recall@${train.top_k}
  mode: max
  verbose: True
  save_top_k: 1
  filename: "checkpoint-val_recall@${train.top_k}_{val_recall@${train.top_k}:.4f}-epoch_{epoch:02d}"
  auto_insert_metric_name: False

prediction_callbacks:
  - _target_: callbacks.custom_callbacks.GoldenRetrieverPredictionCallback
    k: ${train.top_k}
    batch_size: 64
    other_callbacks:
      - _target_: callbacks.evaluation_callbacks.TopKEvaluationCallback
        k: ${train.top_k}
        batch_size: 64
  - _target_: callbacks.custom_callbacks.NegativeAugmentationCallback
    k: ${train.top_k}
    metric_to_monitor: val_recall@${train.top_k}
    threshold: 0.88
    max_negatives: 5
    batch_size: 64
    stages: [val]
    dataset:
      _target_: data.datasets.DPRDataset
      name: "train_augmented"
      contexts_path: ${data.contexts_path}
      tokenizer: ${model.language_model}
      path:
        - "data/dpr-like/srl/ontonotes/ontonotes.train.predicates.json"
