# reproducibility
seed: 42

export: False
float32_matmul_precision: "medium"
top_k: 100

only_test: False

# pl_trainer
pl_trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  num_nodes: 1
  strategy: null
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  val_check_interval: 0.5  # you can specify an int "n" here => validation every "n" steps
  max_epochs: 40
  deterministic: warn
  fast_dev_run: False
  precision: 32
  resume_from_checkpoint: null

# early stopping callback
# "early_stopping_callback: null" will disable early stopping
early_stopping_callback:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_recall@${train.top_k}
  mode: max
  patience: 15

# model_checkpoint_callback
# "model_checkpoint_callback: null" will disable model checkpointing
model_checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_recall@${train.top_k}
  mode: max
  verbose: True
  save_top_k: 1
  filename: 'checkpoint-val_recall@${train.top_k}_{val_recall@${train.top_k}:.4f}-epoch_{epoch:02d}'
  auto_insert_metric_name: False

prediction_callbacks:
  - _target_: callbacks.custom_callbacks.GoldenRetrieverPredictionCallback
    k: ${train.top_k}
    batch_size: 64
    other_callbacks:
      - _target_: callbacks.custom_callbacks.NYTTopKEvaluationCallback
        k: 5
        batch_size: 64
        label_mapping:
          /people/person/nationality:
            - The country that a person holds citizenship in
            - A person's citizenship country
            - The country a person holds citizenship in
          /sports/sports_team/location:
            - The place where a sports team is headquartered
            - The location where a sports team is based
            - The headquarters location of a sports team
          /location/country/administrative_divisions:
            - The subdivisions within a country
            - Divisions within a country
            - The country's administrative territorial entity
          /business/company/major_shareholders:
            - The shareholders that own a significant portion of a company
            - Shareholders owning a significant portion of a company
            - The shareholders of a company
          /people/ethnicity/people:
            - The country of origin for an ethnic group
            - Origin country of an ethnic group
            - The country of origin of an ethnic group
          /people/ethnicity/geographic_distribution:
            - The geographical spread of an ethnic group
            - Geographical spread of an ethnic group
            - The geographical distribution of an ethnic group
          /business/company_shareholder/major_shareholder_of:
            - A major shareholder in a company
            - A company's major shareholder
            - A company's major shareholders
          /location/location/contains:
            - A location that encloses another location
            - A location located within another location
            - A location enclosed in another location
          /business/company/founders:
            - The people who started a company
            - Founders of a company
            - The individuals who established a company
          /business/person/company:
            - The current employer of a person
            - A person's current employer
            - An individual's current place of employment
          /business/company/advisors:
            - Advisors for a company
            - A company's advisors
            - Individuals who provide guidance to a company
          /people/deceased_person/place_of_death:
            - The location where a deceased person passed away
            - A deceased person's place of death
            - The location of death of a deceased person
          /business/company/industry:
            - The field in which a company operates
            - A company's industry
            - The sector in which a company operates
          /people/person/ethnicity:
            - The ethnic background of a person
            - A person's ethnicity
            - An individual's ethnic background
          /people/person/place_of_birth:
            - The birth place of a person
            - A person's place of birth
            - The location where a person was born
          /location/administrative_division/country:
            - The country that an administrative division belongs to
            - Country of an administrative division
            - The country where an administrative division is located
          /people/person/place_lived:
            - The places where a person has lived
            - A person's residence
            - The locations where an individual has lived
          /sports/sports_team_location/teams:
            - The sports teams located in a specific location
            - Sports teams based in a location
            - The teams based in a location
          /people/person/children:
            - The child of a person
            - A person's child
            - An individual's offspring
          /people/person/religion:
            - The religion of a person
            - A person's religion
            - An individual's religious beliefs
          /location/neighborhood/neighborhood_of:
            - The location that a neighborhood is located in
            - Neighborhood of a location
            - The location where a neighborhood is situated
          /location/country/capital:
            - The capital city of a country
            - Capital of a country
            - The city that serves as the administrative center of a country
          /business/company/place_founded:
            - The location where a company was established
            - Location of a company's formation
            - The place where a company was founded
          /people/person/profession:
            - The occupation of a person
            - A person's profession
            - An individual's chosen career
