# reproducibility
seed: 42

export: False
float32_matmul_precision: "medium"
top_k: 100

only_test: False

pl_trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  num_nodes: 1
  strategy: null
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  val_check_interval: 0.5  # you can specify an int "n" here => validation every "n" steps
  max_epochs: 0
  max_steps: 100_000
  deterministic: warn
  fast_dev_run: False
  precision: 16

# early stopping callback
# "early_stopping_callback: null" will disable early stopping
early_stopping_callback:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_recall@${train.top_k}
  mode: max
  patience: 10

# model_checkpoint_callback
# "model_checkpoint_callback: null" will disable model checkpointing
model_checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_recall@${train.top_k}
  mode: max
  verbose: True
  save_top_k: 1
  filename: 'checkpoint-val_recall@${train.top_k}_{val_recall@${train.top_k}:.4f}-epoch_{epoch:02d}'
  auto_insert_metric_name: False

prediction_callbacks:
  - _target_: callbacks.custom_callbacks.GoldenRetrieverPredictionCallback
    k: ${train.top_k}
    batch_size: 256
    use_faiss: False
    other_callbacks:
      - _target_: callbacks.custom_callbacks.TopKEvaluationCallback
        k: ${train.top_k}
      - _target_: callbacks.custom_callbacks.TopKEvaluationCallback
        k: 50
      - _target_: callbacks.custom_callbacks.TopKEvaluationCallback
        k: 20
  - _target_: callbacks.custom_callbacks.NegativeAugmentationCallback
    k: ${train.top_k}
    metric_to_monitor: val_recall@${train.top_k}
    threshold: 0.70
    max_negatives: 10
    batch_size: 256
    stages: [val]
    dataset:
      _target_: ${data.datamodule.datasets.train._target_}
      name: 'train_augmented'
      contexts_path: ${data_overrides.contexts_path}
      max_question_length: 512
      max_context_length: 512
      tokenizer: ${model.language_model}
      path: ${data_overrides.train_path}
      output_dir: null
