wandb_log_model: true
wandb_online_mode: false
wandb_watch: all
wandb_kwargs: null
model_checkpointing: true
checkpoint_dir: null
checkpoint_filename: null
save_top_k: 1
save_last: false
checkpoint_kwargs: null
prediction_batch_size: 128
max_hard_negatives_to_mine: 15
hard_negatives_threshold: 0.0
metrics_to_monitor_for_hard_negatives: null
mine_hard_negatives_with_probability: 1.0
seed: 42
float32_matmul_precision: medium
retriever: null
train_dataset: null
train_batch_size: null
train_dataset_kwargs: {}
val_dataset: null
val_batch_size: null
val_dataset_kwargs: {}
test_dataset: null
test_batch_size: null
test_dataset_kwargs: {}
num_workers: null
optimizer: null
lr: null
weight_decay: null
lr_scheduler: null
num_warmup_steps: null
loss: null
callbacks: null
