language_model: "sentence-transformers/all-MiniLM-L6-v2"

pl_module:
  _target_: models.pl_modules.GoldenRetrieverPLModule
  model:
    _target_: models.model.GoldenRetriever
    question_encoder:
      _target_: models.model.SentenceEncoder
      language_model: ${model.language_model}
    context_encoder:
      _target_: models.model.SentenceEncoder
      language_model: ${model.language_model}
    loss_type:
      _target_: models.losses.MultiLabelNCELoss
      reduction: "sum"
  optim_params:
    optimizer: "radam"
    use_scheduler: false
    lr: 1e-5
    weight_decay: 0
    num_warmup_steps: 10
    num_training_steps: 1000
