language_model: "sentence-transformers/all-MiniLM-L6-v2"

pl_module:
  _target_: models.pl_modules.GoldenRetrieverPLModule
  model:
    _target_: models.model.GoldenRetriever
    question_encoder:
      _target_: models.model.SentenceEncoder
      language_model: ${model.language_model}
    context_encoder:
      _target_: models.model.SentenceEncoder
      language_model: ${model.language_model}
    loss_type:
      _target_: models.losses.MultiLabelNCELoss
      reduction: "sum"
  optimizer:
    _target_: torch.optim.RAdam
    lr: 1e-5
    betas: [0.9, 0.999]
    eps: 1e-08
    weight_decay: 0
  lr_scheduler:
    _target_: transformers.get_linear_schedule_with_warmup
    num_warmup_steps: null
    num_training_steps: null
