language_model: "sentence-transformers/all-MiniLM-L6-v2"

pl_module:
  _target_: models.pl_modules.GoldenRetrieverPLModule
  model:
    _target_: models.model.GoldenRetriever
    question_encoder:
      _target_: models.model.SentenceEncoder
      language_model: ${model.language_model}
      pooling_strategy: "mean"
    context_encoder:
      _target_: models.model.SentenceEncoder
      language_model: ${model.language_model}
      pooling_strategy: "mean"
    loss_type:
      _target_: models.losses.MultiLabelNCELoss
      reduction: "sum"
  optimizer:
    _target_: torch.optim.RAdam
    lr: 1e-5
    weight_decay: 0.0
  lr_scheduler: null
  grouped_parameters: False
  warmup_steps_ratio: 0.1
