language_model: "sentence-transformers/all-MiniLM-L12-v2"

pl_module:
  _target_: golden_retriever.models.pl_modules.GoldenRetrieverPLModule
  model:
    _target_: golden_retriever.models.model.GoldenRetriever
    question_encoder:
      _target_: golden_retriever.models.model.SentenceEncoder
      language_model: ${model.language_model}
      pooling_strategy: "mean"
    context_encoder:
      _target_: golden_retriever.models.model.SentenceEncoder
      language_model: ${model.language_model}
      pooling_strategy: "mean"
    loss_type: ${loss}
    projection_size: 384
    layer_norm: True
  optimizer: ${optimizer}
  lr_scheduler: ${scheduler}
  grouped_parameters: False
  warmup_steps_ratio: 0.1
