# Required to make the "experiments" dir the default one for the output of the models
hydra:
  run:
    dir: ./experiments/${model_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

model_name: ${model.language_model}-inbatch # used to name the model in wandb
project_name: golden-retriever-mosaico # used to name the project in wandb

data:
  max_contexts_per_batch: 400
  max_questions_per_batch: 64
  prefetch_batches: True
  from_generator: False
  use_topics: True
  contexts_path: "data/dpr-like/el/definitions.txt"
  
  datamodule:
    _target_: goldenretriever.lightning_modules.pl_data_modules.PLDataModule
    tokenizer: ${model.language_model}
    datasets:
      train:
        _target_: goldenretriever.data.dpr.datasets.InBatchNegativesDPRIterableDataset
        name: 'train'
        contexts_path: ${data.contexts_path}
        max_context_length: 64
        max_questions_per_batch: ${data.max_questions_per_batch}
        prefetch_batches: ${data.prefetch_batches}
        from_generator: ${data.from_generator}
        max_contexts_per_batch: ${data.max_contexts_per_batch}
        # subsample: 0.2
        shuffle: True
        use_topics: ${data.use_topics}
        path: "data/dpr-like/el/mosaico/first_1M.jsonl"

      val:
        - _target_: goldenretriever.data.dpr.datasets.InBatchNegativesDPRIterableDataset
          name: 'val'
          contexts_path: ${data.contexts_path}
          max_context_length: 64
          max_questions_per_batch: ${data.max_questions_per_batch}
          prefetch_batches: ${data.prefetch_batches}
          from_generator: ${data.from_generator}
          max_contexts_per_batch: ${data.max_contexts_per_batch}
          use_topics: ${data.use_topics}
          path: "data/dpr-like/el/mosaico/val.jsonl"

      test:
        - _target_: goldenretriever.data.dpr.datasets.InBatchNegativesDPRIterableDataset
          name: 'test'
          contexts_path: ${data.contexts_path}
          max_context_length: 64
          max_questions_per_batch: ${data.max_questions_per_batch}
          prefetch_batches: ${data.prefetch_batches}
          from_generator: ${data.from_generator}
          max_contexts_per_batch: ${data.max_contexts_per_batch}
          use_topics: ${data.use_topics}
          path: "data/dpr-like/el/mosaico/val.jsonl"

model:

loss:

optimizer:

train:

defaults:
  - _self_
  - train: mosaico_train
  - model: golden_retriever
  - loss: nce_loss
  - optimizer: radamw
  - scheduler: linear_scheduler
  - data: iterable_in_batch_negatives
  - evaluation: default_evaluation
  - logging: wandb_logging
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
